import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Random;


public class GamePlay implements ActionListener {

    private GUI gui;
    private Players[] currentPlayers;
    private Players player;
    private Phrases phrases;
    private Hosts host;
    private String hostName;
    private JFrame frame;
    private JLabel hostLabel;
    private String playerName;

    public GamePlay(GUI gui) {
        this.gui = gui;
        this.currentPlayers = new Players[3];
        this.player = new Players();
        this.phrases = new Phrases();
    }


    @Override
    public void actionPerformed(ActionEvent e) {
        GUI gui= null;
        try {
            gui = new GUI();
        } catch (IOException ex) {
            throw new RuntimeException(ex);
        }
        ImageIcon icon;
        Object source = e.getSource();
        if (source == gui.addPlayerMenuItem) {
            playerName = JOptionPane.showInputDialog(gui.getFrame(), "Enter the name of the new Player:");
            if (playerName != null && !playerName.isEmpty()) {
                // Find an empty slot for the player
                for (int i = 0; i < 3; i++) {
                    if (currentPlayers[i] == null) {
                        Players newPlayer = new Players();  // Create a new Players object
                        newPlayer.setFirstNoLast(playerName);
                        currentPlayers[i] = newPlayer;
                        gui.currentPlayerIndex = i; // Set the current player index to the newly added player
                        break;
                    }
                }
                gui.updatePlayersLabel(gui.currentPlayerIndex);
                gui.updateCurrentPlayerMoney(gui.currentPlayerIndex);

            }
        } else if (source == gui.addHostMenuItem)    // Triggered when "Add Host" button is clicked
        {
            // If host name hasn't been entered yet, update host label
            if (hostLabel.getText().equals("Host Name:")) {
                hostName = JOptionPane.showInputDialog(frame, "Enter the name of the Host:");
                gui.updateHostLabel(hostName);
                host = new Hosts(hostName);
            }
            // Get the phrase from the host
            String playingPhrase = gui.promptForPhrase();
            Phrases.setGamePhrase(playingPhrase);
            gui.updatePhraseLabel(Phrases.getPlayingPhrase());
        } else if (source == gui.layoutMenuItem) {
            JOptionPane.showMessageDialog(frame, "I decided to use the default JFrame layout manager for my game. \n" +
                    "I chose this option because I could easily set the bounds of each component, \n" +
                    "allowing for the most flexibility in my game's design.");
        } else if(source == gui.attributionMenuItem) {
            JOptionPane.showMessageDialog(frame, "Icons:\n" + "money_img.png was generated by DALLE AI through Canva\n" +
                    "prize_img.png was generated by DALL-E AI through Canva\n" + "Sounds:\n" +
                    "money_mp3.wav was found on https://pixabay.com/sound-effects/search/ching/\n" +
                    "prize.wav was found on https://mixkit.co/free-sound-effects/win/\n" +
                    "wheel.gif was found on https://giphy.com/gifs/BigTimeGaming-official-btg-wof-big-time-gaming-8wVRtdu0M1u0AvcDVM");
        } else if (source == gui.startTurnButton) {
            if (!gui.saveGameMessages.isSelected()) {
                gui.clearMessagesInTextArea();
            }
            if (gui.displayImage != null) {
                // Remove the displayImage JLabel and set its icon to null
                frame.remove(gui.displayImage);
                gui.displayImage.setIcon(null);
                frame.repaint();
            }
            gui.image = new ImageIcon("wheel.gif");
            gui.displayImage.setIcon(gui.image);
            gui.displayImage.setBounds(20, 225, 180, 110);
            frame.add(gui.displayImage);
            frame.repaint();

            if ( (playerName != null && !playerName.isEmpty()) && (!hostLabel.getText().equals("Host Name:")) ) {
                gui.updateCurrentPlayerLabel();
                boolean gameWon = false;
                String guessedLetter = JOptionPane.showInputDialog(frame, "Enter a letter to guess:");
                boolean turnResult = false;
                try {
                    turnResult = Turn.takeTurn(currentPlayers[gui.currentPlayerIndex], host, phrases, guessedLetter);
                } catch (MultipleLettersException ex) {
                    JOptionPane.showMessageDialog(frame, "Please enter one letter at a time");
                }
                boolean continuePlaying = true;

                if (turnResult) {
                    JLabel displayImage = null;
                    gui.updatePhraseLabel(Phrases.getPlayingPhrase());
                    Random random = new Random();
                    int randomPrizeType = random.nextInt(2);

                    if (displayImage != null) {
                        // Remove the displayImage JLabel and set its icon to null
                        frame.remove(displayImage);
                        displayImage.setIcon(null);
                        frame.repaint();
                    }

                    displayImage = new JLabel();
                    try {
                        if (randomPrizeType == 0) {
                            ImageIcon image = new ImageIcon("money_img.png");
                            // Play money audio
                            String soundTrack = "money_mp3.wav";
                            gui.setAudioFile(soundTrack);
                            gui.playAudio();
                            double CORRECT_GUESS_AMOUNT = 100.0; // Amount to increase for a correct guess
                            double INCORRECT_GUESS_AMOUNT = 50.0; // Amount to decrease for an incorrect guess
                            Money money = new Money(CORRECT_GUESS_AMOUNT, INCORRECT_GUESS_AMOUNT);
                            // display winnings and update user's money
                            gui.currentPlayerMoney += CORRECT_GUESS_AMOUNT;
                            gui.currentPlayerMoneyLabel.setText("Money: $" + gui.currentPlayerMoney);
                            // switch to next player
                            gui.currentPlayerIndex = (gui.currentPlayerIndex + 1) % 3;
                            gui.updatePlayersLabel(gui.currentPlayerIndex); // Update players label
                            gui.updateCurrentPlayerLabel();
                            money.displayWinnings(frame, gui.gameMessagesTextArea, player, turnResult);
                        } else {
                            // Physical Prize
                            gui.image = new ImageIcon("prize_img.png");
                            // Play prize audio
                            String soundTrack = "prize.wav";
                            gui.setAudioFile(soundTrack);
                            gui.playAudio();
                            // Remove the displayImage JLabel and set its icon to null
                            frame.remove(displayImage);
                            displayImage.setIcon(null);

                            // Repaint the frame to update the display
                            frame.repaint();
                            Physical physicalPrize = new Physical();
                            physicalPrize.displayWinnings(frame, gui.gameMessagesTextArea, player, turnResult);
                        }
                        displayImage.setIcon(gui.image);
                        displayImage.setBounds(20, 225, 180, 110);
                        frame.add(displayImage);
                        frame.repaint();
                    } catch (Exception exception) {
                        System.out.println("IMAGE NOT FOUND");
                    }

                    if (!phrases.getPlayingPhrase().contains("_")) {
                        gameWon = true;
                        if (gameWon) {
                            int option = JOptionPane.showConfirmDialog(frame, "You solved the puzzle and won the game!\nPlay another game? (Y/N)", "Game Over", JOptionPane.YES_NO_OPTION);
                            if (option == JOptionPane.YES_OPTION) {
                                try {
                                    gui.stopAudio();
                                } catch (IOException ex) {
                                    throw new RuntimeException(ex);
                                }
                                gui.restartGame();
                            } else {
                                System.exit(0);
                            }
                        }
                    }
                }
            }
            else {
                JOptionPane.showMessageDialog(frame, "Please enter host and player names first");
            }
        }
    }
    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                GUI gui = null;
                try {
                    gui = new GUI();
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
                new GamePlay(gui);
            }
        });
    }

}

